### ISSUE TITLE
the version of DOTA dataset

### ISSUE THREAD

**Issue by Lausen-Ng** [YinongGuo/RSVC2021-Dataset#1]
Thanks for your excellent work! I have a question here.

What is the version of 'DOTA DataSet' used in the RSVC2021-Dataset? This is important for me to construct the dataset.

Thanks!

**Comment by YinongGuo** [comment]
The version of DOTA we used is DOTA v1.5.

**Comment by Lausen-Ng** [comment]
> 

Thanks very much!
